
general {
    hide_cursor = true
    grace = 0
    scale = 1.5
}

background {
    monitor =
    path = /home/nikin/Pictures/ferrari_sf_24_2024_4k-3840x2160.jpg
    blur_passes = 3
    blur_size = 8
}

label {
    monitor =
    text = $TIME
    font_size = 120
    position = 0, 180
    color = rgb(255,255,255)
    font_family = monospace
}

label {
    monitor =
    text = %A, %d %B %Y
    font_size = 34
    position = 0, 110
    color = rgba(255,255,255,0.85)
}

label {
    monitor =
    text = Welcome, Nikin
    font_size = 26
    position = 0, -80
    color = rgba(255,255,255,0.9)
}

input-field {
    monitor =
    size = 420, 70
    position = 0, -160

    dots_center = true
    dots_spacing = 0.35
    dots_rounding = 15

    font_size = 28
    inner_color = rgba(0,0,0,0.6)
    outer_color = rgba(255,255,255,0.4)
    outline_thickness = 3

    fade_on_empty = false
}
